// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_ISTLabel;
lv_obj_t * ui_TimeLabel;
lv_obj_t * ui_UKLabel;
lv_obj_t * ui_UKTimeLabel;
lv_obj_t * ui_DateLabel;
lv_obj_t * ui_DayLabel;
lv_obj_t * ui_StatusLabel;
lv_obj_t * ui_BrightnessUpBtn;
lv_obj_t * ui_BrightnessUpLabel;
lv_obj_t * ui_BrightnessDownBtn;
lv_obj_t * ui_BrightnessDownLabel;
lv_obj_t * ui_ThemeBtn;
lv_obj_t * ui_ThemeLabel;
lv_obj_t * ui_FormatBtn;
lv_obj_t * ui_FormatLabel;
lv_obj_t * ui_TimeArea;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void updateClockDisplay(const char* istTime, const char* ukTime, const char* date, const char* day)
{
    if (ui_TimeLabel) {
        lv_label_set_text(ui_TimeLabel, istTime);
        // Serial.print("IST Time updated: ");
        // Serial.println(istTime);
    }
    if (ui_UKTimeLabel) {
        lv_label_set_text(ui_UKTimeLabel, ukTime);
        // Serial.print("UK Time updated: ");
        // Serial.println(ukTime);
    }
    if (ui_DateLabel) {
        lv_label_set_text(ui_DateLabel, date);
    }
    if (ui_DayLabel) {
        lv_label_set_text(ui_DayLabel, day);
    }
}

void ui_event_BrightnessUp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        increaseBrightness();
    }
}

void ui_event_BrightnessDown(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        decreaseBrightness();
    }
}

void ui_event_ThemeChange(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    
    if(event_code == LV_EVENT_PRESSED) {
        // Visual feedback on press
        lv_obj_set_style_bg_color(target, lv_color_hex(0x606060), LV_PART_MAIN | LV_STATE_DEFAULT);
    }
    else if(event_code == LV_EVENT_RELEASED || event_code == LV_EVENT_CLICKED) {
        // Restore button color
        lv_obj_set_style_bg_color(target, lv_color_hex(0x404040), LV_PART_MAIN | LV_STATE_DEFAULT);
        
        if(event_code == LV_EVENT_CLICKED) {
            changeColorTheme();
        }
    }
}

void ui_event_FormatToggle(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        toggleTimeFormat();
    }
}

void ui_event_TimeTouch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        showTimeDetails();
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
