// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_ISTLabel;
extern lv_obj_t * ui_TimeLabel;
extern lv_obj_t * ui_UKLabel;
extern lv_obj_t * ui_UKTimeLabel;
extern lv_obj_t * ui_DateLabel;
extern lv_obj_t * ui_DayLabel;
extern lv_obj_t * ui_StatusLabel;
extern lv_obj_t * ui_BrightnessUpBtn;
extern lv_obj_t * ui_BrightnessUpLabel;
extern lv_obj_t * ui_BrightnessDownBtn;
extern lv_obj_t * ui_BrightnessDownLabel;
extern lv_obj_t * ui_ThemeBtn;
extern lv_obj_t * ui_ThemeLabel;
extern lv_obj_t * ui_FormatBtn;
extern lv_obj_t * ui_FormatLabel;
extern lv_obj_t * ui_TimeArea;

// Global variables for interactive features
extern int currentTheme;
extern bool use24HourFormat;
extern unsigned long lastInteractionTime;
extern bool buttonsVisible;

// Event functions
void ui_event_BrightnessUp(lv_event_t * e);
void ui_event_BrightnessDown(lv_event_t * e);
void ui_event_ThemeChange(lv_event_t * e);
void ui_event_FormatToggle(lv_event_t * e);
void ui_event_TimeTouch(lv_event_t * e);

// Function to update clock display
void updateClockDisplay(const char* istTime, const char* ukTime, const char* date, const char* day);

// Interactive function declarations
void applyWhiteTheme();
void increaseBrightness();
void decreaseBrightness();
void changeColorTheme();
void toggleTimeFormat();
void showTimeDetails();
void hideButtons();
void showButtons();
void updateStatusMessage(const char* message);
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
