// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT); // Black background
    lv_obj_set_style_bg_opa(ui_Screen1, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT); // Ensure background is opaque

    // Create IST timezone label
    ui_ISTLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_ISTLabel, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_ISTLabel, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_ISTLabel, -200);
    lv_obj_set_y(ui_ISTLabel, -180);
    lv_obj_set_align(ui_ISTLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ISTLabel, "IST");
    lv_obj_set_style_text_font(ui_ISTLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_ISTLabel, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT); // Cyan color

    // Create IST time label
    ui_TimeLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_TimeLabel, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_TimeLabel, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_TimeLabel, -200);
    lv_obj_set_y(ui_TimeLabel, -130);
    lv_obj_set_align(ui_TimeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimeLabel, "00:00:00");
    lv_obj_set_style_text_font(ui_TimeLabel, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_TimeLabel, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT); // Green color
    lv_obj_set_style_text_letter_space(ui_TimeLabel, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Create UK timezone label  
    ui_UKLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_UKLabel, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_UKLabel, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_UKLabel, 200);
    lv_obj_set_y(ui_UKLabel, -180);
    lv_obj_set_align(ui_UKLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_UKLabel, "UK");
    lv_obj_set_style_text_font(ui_UKLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_UKLabel, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT); // Cyan color

    // Create UK time label
    ui_UKTimeLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_UKTimeLabel, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_UKTimeLabel, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_UKTimeLabel, 200);
    lv_obj_set_y(ui_UKTimeLabel, -130);
    lv_obj_set_align(ui_UKTimeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_UKTimeLabel, "00:00:00");
    lv_obj_set_style_text_font(ui_UKTimeLabel, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_UKTimeLabel, lv_color_hex(0xFF8000), LV_PART_MAIN | LV_STATE_DEFAULT); // Orange color
    lv_obj_set_style_text_letter_space(ui_UKTimeLabel, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Create date label
    ui_DateLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_DateLabel, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_DateLabel, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_DateLabel, 0);
    lv_obj_set_y(ui_DateLabel, -20);
    lv_obj_set_align(ui_DateLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DateLabel, "Loading...");
    lv_obj_set_style_text_font(ui_DateLabel, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_DateLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT); // White color

    // Create day label
    ui_DayLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_DayLabel, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_DayLabel, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_DayLabel, 0);
    lv_obj_set_y(ui_DayLabel, 40);
    lv_obj_set_align(ui_DayLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DayLabel, "---");
    lv_obj_set_style_text_font(ui_DayLabel, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_DayLabel, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT); // Cyan color

    // Add brightness control buttons
    ui_BrightnessUpBtn = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_BrightnessUpBtn, 80);
    lv_obj_set_height(ui_BrightnessUpBtn, 60);
    lv_obj_set_x(ui_BrightnessUpBtn, 300);
    lv_obj_set_y(ui_BrightnessUpBtn, -25);
    lv_obj_set_align(ui_BrightnessUpBtn, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_BrightnessUpBtn, lv_color_hex(0x404040), LV_PART_MAIN | LV_STATE_DEFAULT);
    
    ui_BrightnessUpLabel = lv_label_create(ui_BrightnessUpBtn);
    lv_obj_center(ui_BrightnessUpLabel);
    lv_label_set_text(ui_BrightnessUpLabel, "+");
    lv_obj_set_style_text_font(ui_BrightnessUpLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BrightnessUpLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrightnessDownBtn = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_BrightnessDownBtn, 80);
    lv_obj_set_height(ui_BrightnessDownBtn, 60);
    lv_obj_set_x(ui_BrightnessDownBtn, 300);
    lv_obj_set_y(ui_BrightnessDownBtn, 75);
    lv_obj_set_align(ui_BrightnessDownBtn, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_BrightnessDownBtn, lv_color_hex(0x404040), LV_PART_MAIN | LV_STATE_DEFAULT);
    
    ui_BrightnessDownLabel = lv_label_create(ui_BrightnessDownBtn);
    lv_obj_center(ui_BrightnessDownLabel);
    lv_label_set_text(ui_BrightnessDownLabel, "-");
    lv_obj_set_style_text_font(ui_BrightnessDownLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_BrightnessDownLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Add color theme button
    ui_ThemeBtn = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_ThemeBtn, 80);
    lv_obj_set_height(ui_ThemeBtn, 60);
    lv_obj_set_x(ui_ThemeBtn, -300);
    lv_obj_set_y(ui_ThemeBtn, -25);
    lv_obj_set_align(ui_ThemeBtn, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_ThemeBtn, lv_color_hex(0x404040), LV_PART_MAIN | LV_STATE_DEFAULT);
    
    ui_ThemeLabel = lv_label_create(ui_ThemeBtn);
    lv_obj_center(ui_ThemeLabel);
    lv_label_set_text(ui_ThemeLabel, "T");
    lv_obj_set_style_text_font(ui_ThemeLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_ThemeLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Add time format toggle button
    ui_FormatBtn = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_FormatBtn, 80);
    lv_obj_set_height(ui_FormatBtn, 60);
    lv_obj_set_x(ui_FormatBtn, -300);
    lv_obj_set_y(ui_FormatBtn, 75);
    lv_obj_set_align(ui_FormatBtn, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_FormatBtn, lv_color_hex(0x404040), LV_PART_MAIN | LV_STATE_DEFAULT);
    
    ui_FormatLabel = lv_label_create(ui_FormatBtn);
    lv_obj_center(ui_FormatLabel);
    lv_label_set_text(ui_FormatLabel, "12H");
    lv_obj_set_style_text_font(ui_FormatLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_FormatLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Add touch time area for settings
    ui_TimeArea = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_TimeArea, 600);
    lv_obj_set_height(ui_TimeArea, 120);
    lv_obj_set_x(ui_TimeArea, 0);
    lv_obj_set_y(ui_TimeArea, -80);
    lv_obj_set_align(ui_TimeArea, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_opa(ui_TimeArea, LV_OPA_TRANSP, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TimeArea, LV_OPA_TRANSP, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Add WiFi status label at the bottom
    ui_StatusLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_StatusLabel, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_StatusLabel, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_StatusLabel, 0);
    lv_obj_set_y(ui_StatusLabel, 180);
    lv_obj_set_align(ui_StatusLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StatusLabel, "Initializing...");
    lv_obj_set_style_text_font(ui_StatusLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_StatusLabel, lv_color_hex(0x888888), LV_PART_MAIN | LV_STATE_DEFAULT); // Gray color

    // Add event callbacks for interactive elements
    lv_obj_add_event_cb(ui_BrightnessUpBtn, ui_event_BrightnessUp, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_BrightnessDownBtn, ui_event_BrightnessDown, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_ThemeBtn, ui_event_ThemeChange, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_FormatBtn, ui_event_FormatToggle, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_TimeArea, ui_event_TimeTouch, LV_EVENT_CLICKED, NULL);

}
