// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void buttonClick(lv_event_t * e)
{
	// Your code here
}
extern "C" {
  #include "../modbus_relay_control.ino"
}

void buttonClick_1(lv_event_t * e) {
	static bool state1 = false;
	state1 = !state1;
	setRelayCoil(0, state1);
	lv_label_set_text(ui_Label1, state1 ? "ON" : "OFF");
}

void buttonClick_2(lv_event_t * e) {
	static bool state2 = false;
	state2 = !state2;
	setRelayCoil(1, state2);
	lv_label_set_text(ui_Label2, state2 ? "ON" : "OFF");
}

void buttonClick_3(lv_event_t * e) {
	static bool state3 = false;
	state3 = !state3;
	setRelayCoil(2, state3);
	lv_label_set_text(ui_Label3, state3 ? "ON" : "OFF");
}

void buttonClick_4(lv_event_t * e) {
	static bool state4 = false;
	state4 = !state4;
	setRelayCoil(3, state4);
	lv_label_set_text(ui_Label4, state4 ? "ON" : "OFF");
}
