// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags


    // Button 1 (Relay 1)
    ui_Button1 = lv_btn_create(ui_Screen1);
    lv_obj_set_size(ui_Button1, 180, 100);
    lv_obj_set_pos(ui_Button1, 40, 60);
    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    ui_Label1 = lv_label_create(ui_Button1);
    lv_label_set_text(ui_Label1, "Relay 1");

    // Button 2 (Relay 2)
    ui_Button2 = lv_btn_create(ui_Screen1);
    lv_obj_set_size(ui_Button2, 180, 100);
    lv_obj_set_pos(ui_Button2, 280, 60);
    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    ui_Label2 = lv_label_create(ui_Button2);
    lv_label_set_text(ui_Label2, "Relay 2");

    // Button 3 (Relay 3)
    ui_Button3 = lv_btn_create(ui_Screen1);
    lv_obj_set_size(ui_Button3, 180, 100);
    lv_obj_set_pos(ui_Button3, 40, 200);
    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    ui_Label3 = lv_label_create(ui_Button3);
    lv_label_set_text(ui_Label3, "Relay 3");

    // Button 4 (Relay 4)
    ui_Button4 = lv_btn_create(ui_Screen1);
    lv_obj_set_size(ui_Button4, 180, 100);
    lv_obj_set_pos(ui_Button4, 280, 200);
    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
    ui_Label4 = lv_label_create(ui_Button4);
    lv_label_set_text(ui_Label4, "Relay 4");

}
