// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

    // Create 5 text display labels
    for(int i = 0; i < 5; i++) {
        ui_TextLabel[i] = lv_label_create(ui_Screen1);
        lv_obj_set_width(ui_TextLabel[i], 780);
        lv_obj_set_height(ui_TextLabel[i], 60); // Height for each line
        lv_obj_set_x(ui_TextLabel[i], 0);
        lv_obj_set_y(ui_TextLabel[i], -150 + (i * 70)); // Distribute lines vertically
        lv_obj_set_align(ui_TextLabel[i], LV_ALIGN_CENTER);
        
        // Set default text for each line
        char defaultText[20];
        sprintf(defaultText, "Line %d", i + 1);
        lv_label_set_text(ui_TextLabel[i], defaultText);
        
        lv_obj_set_style_text_font(ui_TextLabel[i], &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_color(ui_TextLabel[i], lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_align(ui_TextLabel[i], LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_opa(ui_TextLabel[i], LV_OPA_TRANSP, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_label_set_long_mode(ui_TextLabel[i], LV_LABEL_LONG_WRAP);
    }

    // Add status label at the bottom
    ui_StatusLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_StatusLabel, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_StatusLabel, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_StatusLabel, 0);
    lv_obj_set_y(ui_StatusLabel, 200);
    lv_obj_set_align(ui_StatusLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StatusLabel, "Connecting...");
    lv_obj_set_style_text_font(ui_StatusLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_StatusLabel, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_StatusLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

}
